# Generated by Django 4.0 on 2022-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.CharField(max_length=5000)),
                ('product_price', models.IntegerField()),
                ('product_image', models.FileField(upload_to='product')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
