# Generated by Django 4.0 on 2022-03-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(default=False, max_length=100)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
